"""profile table

Revision ID: b019d6cd4f32
Revises: e4459cf3c9ea
Create Date: 2024-02-08 11:40:09.117738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b019d6cd4f32'
down_revision = 'e4459cf3c9ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_favorite_recipes')
    with op.batch_alter_table('favorite_recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_favorite_recipes_profile_id_profiles'), 'profiles', ['profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorite_recipes', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_favorite_recipes_profile_id_profiles'), type_='foreignkey')
        batch_op.drop_column('profile_id')

    op.create_table('_alembic_tmp_favorite_recipes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('recipe_id', sa.INTEGER(), nullable=False),
    sa.Column('profile_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='fk_favorite_recipes_profile_id_profiles'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_favorite_recipes_recipe_id_recipes'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_favorite_recipes_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
