"""journal table

Revision ID: e3b07dda1e92
Revises: a64b7fdfe6d8
Create Date: 2024-02-14 14:25:05.827568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3b07dda1e92'
down_revision = 'a64b7fdfe6d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('journal_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_journal_entries_user_id_users')),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('_alembic_tmp_recipe_associations')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_recipe_associations',
    sa.Column('recipe_id', sa.INTEGER(), nullable=True),
    sa.Column('ingredient_id', sa.INTEGER(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name='fk_recipe_associations_ingredient_id_ingredients'),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], name='fk_recipe_associations_recipe_id_recipes'),
    sa.PrimaryKeyConstraint('recipe_id', 'ingredient_id')
    )
    op.drop_table('journal_entries')
    # ### end Alembic commands ###
